
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%=ENV['DB_DEV']%>

  username: <%=ENV['DB_USER']%>


  password: <%=ENV['DB_PASS']%>

test:
  <<: *default
  database: <%=ENV['DB_TEST']%>
  username: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASS']%>
  
production:
  <<: *default
  database: AZA_production
  username: AZA
  password: <%= ENV["AZA_DATABASE_PASSWORD"] %>
